# 6/22 코로나 보드 '어제' 데이터 스크랩

In [3]:
from IPython.display import display, Image
import os, warnings
import re
warnings.filterwarnings(action='ignore')

from selenium import webdriver
from bs4 import BeautifulSoup


# 웹드라이버 불러와서 버튼 설정하기

driver = webdriver.Chrome('../chromedriver_90')
url = 'https://coronaboard.kr/'
driver.get(url)
import time
time.sleep(3)

from selenium.webdriver import ActionChains
yesterday_button = driver.find_element_by_xpath('//*[@id="global-slide"]/div/div[2]/ul/li[2]/a')
ActionChains(driver).move_to_element(yesterday_button).perform()
yesterday_button.click()

some_tag = driver.find_element_by_id('show-more')
ActionChains(driver).move_to_element(some_tag).perform()
some_tag.click()

ActionChains(driver).move_to_element(some_tag).perform()
some_tag.click()

some_tag = driver.find_element_by_xpath('//*[@id="global-slide"]/div/div[2]/div/div/button')
ActionChains(driver).move_to_element(some_tag).perform()
some_tag.click()

driver.find_element_by_xpath('//*[@id="bs-select-1-0"]').click()
driver.find_element_by_xpath('//*[@id="bs-select-1-1"]').click()
driver.find_element_by_xpath('//*[@id="bs-select-1-5"]').click()



# 차트 데이터 긁어와서 데이터프레임으로 만들기


all_data = []
for i in range(2, 12):
    tmp = '//*[@id="country-table"]/div/div/table/tbody/tr/td[{}]'.format(i)
    sel_ele = driver.find_elements_by_xpath(tmp)

    column_data = []
    for one in sel_ele:
        column_data.append(one.text)

    print( len(sel_ele) )
    all_data.append(column_data)
    print(column_data)
    print()

all_data

import pandas as pd
dict_dat = { "국가":all_data[0],
 "확진자":all_data[1],
 "치료중":all_data[2],
 "위중증":all_data[3],
 "사망자":all_data[4],
 "완치":all_data[5],
 "치명(%)":all_data[6],
 "완치(%)":all_data[7],
 "발생률":all_data[8],
 "인구수":all_data[9]
 }
dat = pd.DataFrame(dict_dat)
dat

221
['미국🇺🇸', '인도🇮🇳', '브라질🇧🇷', '프랑스🇫🇷', '터키🇹🇷', '러시아🇷🇺', '영국🇬🇧', '아르헨티나🇦🇷', '이탈리아🇮🇹', '콜롬비아🇨🇴', '스페인🇪🇸', '독일🇩🇪', '이란🇮🇷', '폴란드🇵🇱', '멕시코🇲🇽', '우크라이나🇺🇦', '페루🇵🇪', '인도네시아🇮🇩', '남아프리카 공화국🇿🇦', '네덜란드🇳🇱', '체코🇨🇿', '칠레🇨🇱', '캐나다🇨🇦', '필리핀🇵🇭', '이라크🇮🇶', '스웨덴🇸🇪', '루마니아🇷🇴', '벨기에🇧🇪', '파키스탄🇵🇰', '포르투갈🇵🇹', '방글라데시🇧🇩', '이스라엘🇮🇱', '헝가리🇭🇺', '일본🇯🇵*', '요르단🇯🇴', '세르비아🇷🇸', '스위스🇨🇭', '말레이시아🇲🇾', '오스트리아🇦🇹', '네팔🇳🇵', '아랍에미레이트🇦🇪', '레바논🇱🇧', '모로코🇲🇦', '사우디아라비아🇸🇦', '에콰도르🇪🇨', '볼리비아🇧🇴', '불가리아🇧🇬', '그리스🇬🇷', '벨라루스🇧🇾', '카자흐스탄🇰🇿', '파라과이🇵🇾', '파나마🇵🇦', '슬로바키아🇸🇰', '튀니지🇹🇳', '크로아티아🇭🇷', '조지아🇬🇪', '우루과이🇺🇾', '코스타리카🇨🇷', '쿠웨이트🇰🇼', '아제르바이잔🇦🇿', '도미니카 공화국🇩🇴', '팔레스타인🇵🇸', '덴마크🇩🇰', '과테말라🇬🇹', '리투아니아🇱🇹', '이집트🇪🇬', '에티오피아🇪🇹', '아일랜드🇮🇪', '바레인🇧🇭', '베네수엘라🇻🇪', '슬로베니아🇸🇮', '몰도바🇲🇩', '온두라스🇭🇳', '오만🇴🇲', '스리랑카🇱🇰', '아르메니아🇦🇲', '태국🇹🇭', '카타르🇶🇦', '보스니아 헤르체고비나🇧🇦', '리비아🇱🇾', '케냐🇰🇪', '쿠바🇨🇺', '나이지리아🇳🇬', '북마케도니아🇲🇰', '대한민국🇰🇷', '미얀마🇲🇲', '라트비아🇱🇻', '알제리🇩🇿', '알바니아🇦🇱', '에스토니아🇪🇪', '잠비아🇿🇲', '노르웨이🇳🇴', '키르기스스탄🇰🇬', '코소보🇽🇰', '우즈베키스탄🇺🇿', '아프가니스탄🇦🇫', '몬테네그로🇲🇪', '몽골🇲🇳', '가나🇬🇭', '핀란드🇫🇮', '중국🇨🇳', '카메룬🇨🇲', '엘살바도르🇸🇻', '나미비아🇳🇦', '키프로스🇨🇾', '모잠비크🇲🇿', '몰디브🇲🇻', '우간다🇺🇬', '룩셈부르크🇱🇺', '보츠와나🇧🇼', '싱가포르🇸🇬', '자메이카🇯🇲', '코트디부아르🇨🇮', '캄보디아🇰🇭', '세네갈🇸🇳', '마다가스카르🇲🇬', '짐바브웨🇿🇼', '콩고민주공화국🇨🇩', '앙골라🇦🇴', '수단🇸🇩', '말라위🇲🇼', '카보베르데🇨🇻', '르완다🇷🇼', '트리니다드 토바고🇹🇹', '몰타 공화국🇲🇹', '호주🇦🇺', '레위니옹🇷🇪', '프랑스령 기아나🇬🇫', '시리아🇸🇾', '가봉🇬🇦', '기니🇬🇳', '모리타니🇲🇷', '수리남🇸🇷', '마요트🇾🇹', '가이아나🇬🇾', '프랑스령 폴리네시아🇵🇫', '에스와티니🇸🇿', '아이티🇭🇹', '파푸아뉴기니🇵🇬', '과들루프🇬🇵', '소말리아🇸🇴', '말리🇲🇱', '세이셸🇸🇨', '대만🇹🇼', '안도라🇦🇩', '토고🇹🇬', '베트남🇻🇳', '부르키나파소🇧🇫', '타지키스탄🇹🇯', '벨리즈🇧🇿', '퀴라소🇨🇼', '콩고공화국🇨🇬', '바하마🇧🇸', '마르티니크🇲🇶', '홍콩🇭🇰', '지부티🇩🇯', '아루바🇦🇼', '레소토🇱🇸', '남수단🇸🇸', '동티모르🇹🇱', '적도 기니🇬🇶', '베냉🇧🇯', '니카라과🇳🇮', '중앙아프리카 공화국🇨🇫', '예멘🇾🇪', '아이슬란드🇮🇸', '감비아🇬🇲', '니제르🇳🇪', '에리트레아🇪🇷', '세인트루시아🇱🇨', '부룬디🇧🇮', '산마리노🇸🇲', '차드🇹🇩', '시에라리온🇸🇱', '지브롤터🇬🇮', '바베이도스🇧🇧', '코모로🇰🇲', '기니비사우🇬🇼', '리히텐슈타인🇱🇮', '라이베리아🇱🇷', '뉴질랜드🇳🇿', '신트마르턴🇸🇽', '모나코🇲🇨', '버뮤다🇧🇲', '터크스 케이커스 제도🇹🇨', '상투메 프린시페🇸🇹', '세인트빈센트 그레나딘🇻🇨', '세인트마틴 섬🇲🇫', '피지🇫🇯', '라오스🇱🇦', '부탄🇧🇹', '모리셔스🇲🇺', '카리브 네덜란드🇧🇶', '맨섬🇮🇲', '앤티가 바부다🇦🇬', '생바르텔레미🇧🇱', '페로 제도🇫🇴', '케이맨 제도🇰🇾', '탄자니아🇹🇿', '왈리스 퓌티나🇼🇫', '세인트키츠 네비스🇰🇳', '브루나이🇧🇳', '영국령 버진아일랜드🇻🇬', '도미니카 연방🇩🇲', '그레나다🇬🇩', '뉴칼레도니아🇳🇨', '앵귈라🇦🇮', '포클랜드 제도🇫🇰', '마카오🇲🇴', '그린란드🇬🇱', '바티칸 시국🇻🇦', '생피에르 미클롱🇵🇲', '몬트세랫🇲🇸', '솔로몬 제도🇸🇧', '서사하라🇪🇭', '잔담(크루즈)🚢', '마셜 제도🇲🇭', '바누아투🇻🇺', '사모아🇼🇸', '세인트헬레나🇸🇭', '미크로네시아🇫🇲']

221
['34,406,059\n(+4,219)', '29,965,292\n(+54,052)', '17,927,928\n(+44,178)', '5,757,311\n(+1,815)', '5,370,299\n(+5,091)', '5,334,204\n(+17,378)', '4,630,040\n(+9,072)', '4,268,789\n(+10,395)', '4,252,976\n(+881)', '3,945,166\n(+27,818)', '3,757,442', '3,730,246\n(+493)', '3,105,620\n(+10,485)', '2,878,840\n(+73)', '2,477,283\n(+1,578)', '2,229,846\n(+323)', '2,029,625\n(+2,896)', '2,004,445\n(+14,536)', '1,823,319\n(+13,155)', '1,679,542\n(+559)', '1,666,082\n(+57)', '1,517,018\n(+5,743)', '1,408,836\n(+713)', '1,364,239\n(+5,224)', '1,292,700\n(+5,235)', '1,084,636', '1,080,282\n(+26)', '1,079,415\n(+331)', '949,175\n(+907)', '865,050', '856,304\n(+4,636)', '839,867\n(+37)', '807,630\n(+202)', '785,969', '746,480\n(+502)', '715,841\n(+88)', '701,994\n(+367)', '701,019\n(+4,611)', '649,670\n(+94)', '622,640\n(+1,584)', '613,993\n(+1,964)', '543,505\n(+134)', '526,651\n(+288)', '475,403\n(+1,212)', '446,441\n(+855)', '422,047\n(+1,086)', '421,032\n(+27)', '418,342\n(+247)', '411,153\n(+475)', '409,580\n(+930)', '406,220\n(+1,145)', '393,727\n(+583)', '391,326\n(+1)', '382,950\n(+1,775)', '359,184\n(+11)', '359,141\n(+260)', '354,865\n(+1,488)', '350,630', '339,032\n(+1,661)', '335,521\n(+28)', '316,787\n(+972)', '312,673\n(+68)', '291,801\n(+149)', '280,507\n(+560)', '278,407\n(+28)', '277,288\n(+532)', '275,194\n(+158)', '269,048', '262,892\n(+465)', '260,740\n(+1,327)', '257,001\n(+19)', '256,140\n(+37)', '253,875\n(+747)', '250,572\n(+2,529)', '239,689\n(+2,028)', '224,253\n(+26)', '221,306\n(+3,175)', '220,930\n(+130)', '204,814', '191,038\n(+290)', '179,075\n(+283)', '167,804\n(+1,436)', '167,206', '155,627\n(+11)', '151,506\n(+357)', '148,022', '136,850\n(+40)', '135,821\n(+235)', '132,490\n(+2)', '130,818\n(+12)', '130,631\n(+1,598)', '129,333\n(+58)', '115,615\n(+585)', '107,247', '106,452\n(+427)', '105,755\n(+1,853)', '100,075', '95,819\n(+2,268)', '94,913', '94,379\n(+45)', '91,604\n(+17)', '80,328', '77,100\n(+403)', '74,682\n(+1,518)', '73,643\n(+61)', '72,507\n(+140)', '71,896\n(+187)', '71,543\n(+1,367)', '70,516', '63,247', '62,430\n(+16)', '49,668\n(+61)', '48,044\n(+13)', '43,446\n(+735)', '42,437\n(+33)', '42,137\n(+14)', '41,779\n(+151)', '37,809', '37,678\n(+74)', '36,347', '34,868\n(+36)', '32,002\n(+38)', '30,813\n(+296)', '30,619\n(+106)', '30,590\n(+1)', '30,352\n(+21)', '28,441', '26,450', '25,118\n(+42)', '24,864', '23,450', '20,336\n(+22)', '20,025\n(+277)', '19,389', '19,096\n(+123)', '18,963', '18,813\n(+2)', '17,371\n(+132)', '17,013\n(+80)', '16,752', '14,852', '14,381\n(+1)', '14,123', '14,080\n(+75)', '13,864\n(+22)', '13,721\n(+6)', '13,483\n(+366)', '13,469\n(+1)', '13,308', '13,004', '12,318\n(+1)', '12,298', '12,295', '12,178', '11,889\n(+3)', '11,587', '11,108\n(+2)', '11,081', '10,770', '8,728\n(+21)', '8,698', '8,140', '7,696', '7,101', '6,885', '6,627', '6,024', '5,469', '5,362\n(+26)', '5,216\n(+5)', '5,121', '5,090', '4,946', '4,816\n(+114)', '4,321', '4,043\n(+2)', '3,908', '3,825', '3,026', '2,995\n(+161)', '2,720\n(+2)', '2,570', '2,548', '2,504', '2,424\n(+1)', '2,362', '2,195\n(+3)', '2,133', '2,090\n(+126)', '2,054\n(+1)', '1,924', '1,701', '1,632\n(+2)', '1,599', '1,263', '1,005', '766\n(+5)', '608', '509', '445', '341\n(+11)', '255\n(+3)', '248', '191', '161', '129', '109', '63', '53', '49', '27', '26', '20', '20', '10', '9', '4', '4', '3', '2', '1']

221
['5,077,577\n(-12,311)', '681,288\n(-44,081)', '1,205,772\n(+6,739)', '89,987\n(+604)', '88,476\n(+809)', '326,070\n(+8,577)', '200,079\n(+6,916)', '289,533\n(-12,014)', '87,710\n(-1,440)', '178,071\n(+4,345)', '132,585', '34,076\n(-1,723)', '262,290\n(-1,560)', '153,363\n(-100)', '274,626\n(-791)', '25,674\n(-370)', 'N/A', '147,728\n(+5,009)', '117,114\n(+6,389)', 'N/A', '2,640\n(-265)', '39,802\n(-899)', '11,760\n(-465)', '55,847\n(-1,832)', '70,911\n(+434)', 'N/A', '2,684\n(-124)', '37,705\n(-8,462)', '34,020\n(+48)', '28,297', '57,196\n(+1,731)', '378\n(+37)', '42,097\n(-754)', '22,248', '6,633\n(-26)', '2,849\n(-198)', '14,628\n(-2,027)', '62,918\n(-897)', '2,625\n(-146)', '53,940\n(-1,592)', '19,246\n(+35)', '6,065\n(+131)', '3,732\n(-12)', '10,584\n(-312)', '9,640\n(-7,150)', '66,811\n(-926)', '10,226\n(+19)', '6,794\n(-1,115)', '4,075\n(+199)', '20,295\n(-44)', '50,628\n(-1,662)', '10,491\n(+30)', '875\n(-14)', '35,950\n(+645)', '535\n(-62)', '8,384\n(-589)', '26,100\n(-1,689)', '74,029', '17,277\n(+187)', '959\n(-22)', '54,858\n(-169)', '2,882\n(+67)', '4,518\n(-393)', '17,873\n(-434)', '8,407\n(-19)', '55,816\n(+46)', '15,963\n(-497)', '11,162', '7,676\n(-606)', '16,849\n(-141)', '1,562\n(-38)', '793\n(-13)', '155,381\n(+662)', '27,660\n(+1,168)', '35,719\n(-15)', '3,642\n(-38)', '33,859\n(+1,116)', '1,912\n(-61)', '15,326', '11,410\n(+53)', '52,915\n(+201)', '8,157\n(+222)', '1,532\n(-7)', '273\n(-78)', '6,234\n(-14)', '11,154', '1,633\n(-411)', '37,619\n(-7)', '118\n(-6)', '2,854\n(-20)', '18,490\n(+61)', '39,591\n(+58)', '8,268\n(+219)', '-34', '3,571\n(-44)', '36,391\n(+1,105)', '303', '31,904\n(+1,902)', '1,239', '47,412\n(+45)', '522\n(+12)', '853', '3,421\n(+118)', '13,842\n(+1,088)', '1,280\n(+61)', '1,610\n(+131)', '5,311\n(-103)', '21,351\n(+1,128)', '404', '3,766', '354\n(-3)', '20,015\n(-96)', '291\n(-13)', '5,002\n(+211)', '365\n(-6)', '765\n(-7)', '2,923\n(+128)', '8,992', '5,143\n(-16)', '3,548', '829\n(+12)', '731\n(-9)', '3,727\n(+167)', '8,274\n(-222)', '23\n(-4)', '170\n(+21)', '1,888', '16,318', '1,535\n(+27)', '442', '1,032', '442\n(-20)', '4,242\n(+112)', '16,251', '1,576\n(+94)', '34', '119\n(-10)', '4,319\n(+98)', '444\n(-7)', '14,273', '6,927', '3,824\n(-10)', '1,563', '12,378\n(+55)', '72\n(+7)', '238\n(+3)', '7,963\n(-36)', '9\n(-2)', '0', '125', '33\n(-3)', '926', '824', '11,982', '65\n(+1)', '5\n(-3)', '28\n(-1)', '4,307', '141', '1,042\n(-17)', '89', '58', '3,283', '144', '1,577', '21', '16', '98', '525\n(-10)', '75\n(-1)', '4,340', '1', '4', '1,470\n(+83)', '16\n(-2)', '10\n(+2)', '17', '198', '12', '795\n(+161)', '23\n(+1)', '61', '41', '10', '17\n(+1)', '11', '248\n(+2)', '722', '1,551\n(+67)', '103\n(-3)', '247', '418', '16\n(+2)', '4', '0', '542', '10\n(+5)', '19', '305', '0', '265\n(+9)', '8\n(+2)', '38', '2', '0', '71', '0', '0', '2', '9', '0', '1', '0', '0', '1', '0', '0', '0', '0', '0', '0']

221
['3,957\n(-38)', '8,944', '8,318', '1,703', '813\n(-16)', '2,300', '210', '7,366\n(-20)', '389\n(-5)', '8,155', '793', '1,210', '3,258\n(-21)', '242\n(+4)', '4,798', '177', '2,521\n(+6)', 'N/A', '546', '193\n(-14)', '8\n(-6)', '3,230\n(-45)', '567', '2,029', '539\n(+4)', '71\n(-1)', '158\n(-3)', '212', '2,238\n(-92)', '97', '1,217\n(+33)', '24\n(-1)', '37\n(-6)', '718', '470', '21\n(+5)', '64\n(-1)', '880', '80\n(-4)', 'N/A', 'N/A', '67', '107\n(-1)', '1,489\n(-27)', '456\n(-11)', '200', '207', '296\n(-5)', 'N/A', '221', '571\n(-1)', '105', '35\n(-1)', '424', '19\n(-6)', 'N/A', '395\n(-2)', '472', '204\n(-5)', 'N/A', '465\n(-26)', '9', '17\n(-2)', '5', '56\n(-6)', '90', '201\n(-11)', '15', '165\n(-25)', '287', '35\n(+1)', '54\n(+2)', '542', '428\n(+14)', 'N/A', 'N/A', '1,436\n(+93)', '74\n(-2)', 'N/A', 'N/A', '113', '146\n(-10)', '11', '25', '137\n(-9)', 'N/A', '42', '29\n(-5)', '3', '5', '1,023\n(+40)', '7', '102', 'N/A', '23', '1,124', '6', '126', '9', '9\n(-3)', 'N/A', '152', '30\n(-2)', '76\n(-3)', '22\n(+1)', '32', '90', '1,026\n(+11)', '1', '1', '1', '8\n(+1)', 'N/A', 'N/A', '7', '62\n(-9)', '10', 'N/A', '18', 'N/A', '22', '23', '13', '22', 'N/A', '1', '32', '36', 'N/A', '17', '24', '16', '36\n(-3)', '6', '21', 'N/A', '10', 'N/A', '7', '23', 'N/A', 'N/A', 'N/A', 'N/A', '3', 'N/A', 'N/A', 'N/A', 'N/A', '1', '4', 'N/A', '3', '5', 'N/A', 'N/A', '14', 'N/A', 'N/A', 'N/A', '1', '5', 'N/A', '2', '23', '1', '3', '2', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', '4', '3', '2', 'N/A', '2', '1', '7', '2', 'N/A', '2', '7', '2', 'N/A', 'N/A', 'N/A', 'N/A', '1', 'N/A', 'N/A', 'N/A', 'N/A', '7', 'N/A', '1', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']

221
['617,166\n(+75)', '388,828\n(+1,667)', '501,918\n(+1,050)', '110,738\n(+14)', '49,185\n(+63)', '129,801\n(+440)', '127,976\n(+6)', '89,043\n(+301)', '127,270\n(+17)', '99,934\n(+599)', '80,652', '90,970\n(+16)', '83,101\n(+136)', '74,829\n(+1)', '231,187\n(+36)', '52,032\n(+16)', '190,425\n(+223)', '54,956\n(+294)', '58,702\n(+112)', '17,727\n(+1)', '30,280', '31,513\n(+121)', '26,076\n(+22)', '23,749\n(+128)', '16,910\n(+25)', '14,537', '32,391\n(+65)', '25,136\n(+4)', '22,007\n(+30)', '17,065', '13,626\n(+78)', '6,428', '29,959\n(+9)', '14,439', '9,662\n(+6)', '7,004\n(+3)', '10,872\n(+3)', '4,477\n(+69)', '10,680', '8,772\n(+46)', '1,763\n(+6)', '7,822\n(+3)', '9,238\n(+1)', '7,691\n(+14)', '21,293\n(+9)', '16,132\n(+44)', '17,990\n(+1)', '12,542\n(+14)', '3,053\n(+9)', '4,242\n(+8)', '11,633\n(+112)', '6,475\n(+7)', '12,496\n(+4)', '14,038\n(+78)', '8,182\n(+8)', '5,175\n(+15)', '5,271\n(+30)', '4,473', '1,870\n(+8)', '4,963\n(+1)', '3,756\n(+2)', '3,551\n(+1)', '2,531\n(+1)', '8,694\n(+49)', '4,367\n(+1)', '15,859\n(+30)', '4,283\n(+3)', '4,941', '1,306\n(+9)', '2,958\n(+15)', '4,415\n(+3)', '6,170\n(+2)', '6,766\n(+7)', '2,741\n(+31)', '2,581\n(+47)', '4,499\n(+1)', '1,658\n(+29)', '583', '9,630', '3,178\n(+4)', '3,456\n(+9)', '1,159\n(+11)', '2,117', '5,477\n(+2)', '2,004\n(+2)', '3,262', '2,496', '3,631\n(+7)', '2,454', '1,268', '1,691\n(+47)', '790', '1,937\n(+6)', '2,256', '718', '4,293\n(+78)', '1,605', '447\n(+11)', '793', '967', '4,636', '1,313', '2,332', '1,164\n(+3)', '374', '848\n(+1)', '206\n(+1)', '660\n(+34)', '818', '940', '34', '1,033\n(+2)', '308\n(+1)', '441\n(+10)', '1,158', '903\n(+2)', '1,672\n(+6)', '879', '859\n(+3)', '2,737', '1,168', '283\n(+2)', '382\n(+3)', '737\n(+5)', '420', '910', '220', '137', '1,845\n(+4)', '158', '168', '481\n(+1)', '460\n(+6)', '174', '447\n(+3)', '142', '677', '385\n(+12)', '173', '229', '775', '524', '55', '569\n(+20)', '127', '128\n(+1)', '67\n(+3)', '167', '90', '328', '125', '161', '241', '98', '210', '155', '107', '329', '115', '19', '120', '103', '188', '98', '1,355', '30', '181', '193', '19', '80', '8', '90', '174', '82', '94', '47', '146', '69', '59', '95', '26', '32', '33', '33', '18', '37', '12', '12', '7', '3', '1', '18', '17', '29', '42', '1', '1', '2', '21', '7', '1', '3', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '1', '0', '1', '2', '0', '1', '0', '0', '0']

221
['28,711,316\n(+16,455)', '28,895,176\n(+96,466)', '16,220,238\n(+36,389)', '5,556,586\n(+1,197)', '5,232,638\n(+4,219)', '4,878,333\n(+8,361)', '4,301,985\n(+2,150)', '3,890,213\n(+22,108)', '4,037,996\n(+2,304)', '3,667,161\n(+22,874)', '3,544,205', '3,605,200\n(+2,200)', '2,760,229\n(+11,909)', '2,650,648\n(+172)', '1,971,470\n(+2,333)', '2,152,140\n(+677)', 'N/A', '1,801,761\n(+9,233)', '1,647,503\n(+6,654)', 'N/A', '1,633,162\n(+322)', '1,445,703\n(+6,521)', '1,371,000\n(+1,156)', '1,284,643\n(+6,928)', '1,204,879\n(+4,776)', 'N/A', '1,045,207\n(+85)', '1,016,574\n(+8,789)', '893,148\n(+829)', '819,688', '785,482\n(+2,827)', '833,061', '735,574\n(+947)', '749,282', '730,185\n(+522)', '705,988\n(+283)', '676,494\n(+2,391)', '633,624\n(+5,439)', '636,365\n(+240)', '559,928\n(+3,130)', '592,984\n(+1,923)', '529,618', '513,681\n(+299)', '457,128\n(+1,510)', '415,508\n(+7,996)', '339,104\n(+1,968)', '392,816\n(+7)', '399,006\n(+1,348)', '404,025\n(+267)', '385,043\n(+966)', '343,959\n(+2,695)', '376,761\n(+546)', '377,955\n(+11)', '332,962\n(+1,052)', '350,467\n(+65)', '345,582\n(+834)', '323,494\n(+3,147)', '272,128', '319,885\n(+1,466)', '329,599\n(+49)', '258,173\n(+1,139)', '306,240', '284,752\n(+541)', '253,940\n(+945)', '265,633\n(+46)', '205,613\n(+456)', '254,948\n(+652)', '252,945', '253,910\n(+1,062)', '240,933\n(+1,453)', '251,024\n(+54)', '249,177\n(+48)', '91,728\n(+78)', '220,171\n(+1,330)', '201,389\n(+1,996)', '216,112\n(+63)', '185,789\n(+2,030)', '218,435\n(+191)', '179,858', '176,450\n(+233)', '122,704\n(+73)', '158,488\n(+1,203)', '163,557\n(+7)', '149,877\n(+87)', '143,268\n(+369)', '133,606', '132,721\n(+451)', '94,571\n(+235)', '129,918\n(+8)', '126,696\n(+32)', '110,450\n(+1,490)', '88,952', '105,410\n(+360)', '105,025', '102,163\n(+471)', '65,071\n(+670)', '98,167', '63,468\n(+355)', '92,881', '46,000', '86,446\n(+5)', '78,162', '71,347\n(+285)', '59,676\n(+427)', '71,989', '70,049\n(+8)', '66,379\n(+289)', '49,532\n(+205)', '69,294', '58,541', '62,042\n(+19)', '28,620\n(+155)', '47,445\n(+25)', '38,003\n(+514)', '40,914\n(+39)', '40,469\n(+19)', '37,184\n(+17)', '27,938', '31,676\n(+87)', '30,062', '32,871\n(+24)', '30,988\n(+45)', '26,704\n(+126)', '21,608\n(+323)', '30,147\n(+5)', '29,272', '26,333', '9,995', '21,738\n(+11)', '24,264', '22,250', '19,413\n(+41)', '15,323\n(+159)', '2,964', '17,073\n(+26)', '18,787', '18,017\n(+12)', '12,667\n(+22)', '16,396\n(+87)', '2,250', '7,150', '10,033\n(+11)', '12,505', '1,133', '13,665\n(+15)', '13,355\n(+2)', '5,453\n(+399)', '13,293\n(+3)', '13,218', '12,551', '12,160\n(+4)', '11,211', '11,230', '98', '11,614\n(+2)', '11,427\n(+3)', '10,973\n(+3)', '6,445', '10,514', '7,667\n(+38)', '8,489', '7,979', '4,225', '6,859', '3,953', '6,576', '5,827', '5,178', '4,818\n(+36)', '5,061\n(+6)', '773', '4,999', '4,768', '3,264\n(+31)', '4,211\n(+2)', '3,986', '3,745', '3,558', '2,955', '2,105', '2,671\n(+1)', '2,477', '2,474', '2,461', '2,389', '2,314', '1,935\n(+1)', '1,399', '532\n(+59)', '1,948\n(+4)', '1,676', '1,265', '1,599', '1,566', '1,221', '462', '755', '587', '183', '438', '75\n(+2)', '244\n(+1)', '209', '189', '160', '58', '109', '63', '51', '40', '27', '25', '19', '20', '8', '7', '4', '3', '3', '2', '1']

221
['1.8', '1.3', '2.8', '1.9', '0.9', '2.4', '2.8', '2.1', '3.0', '2.5', '2.1', '2.4', '2.7', '2.6', '9.3', '2.3', '9.4', '2.7', '3.2', '1.1', '1.8', '2.1', '1.9', '1.7', '1.3', '1.3', '3.0', '2.3', '2.3', '2.0', '1.6', '0.8', '3.7', '1.8', '1.3', '1.0', '1.5', '0.6', '1.6', '1.4', '0.3', '1.4', '1.8', '1.6', '4.8', '3.8', '4.3', '3.0', '0.7', '1.0', '2.9', '1.6', '3.2', '3.7', '2.3', '1.4', '1.5', '1.3', '0.6', '1.5', '1.2', '1.1', '0.9', '3.1', '1.6', '5.7', '1.6', '1.8', '0.5', '1.1', '1.7', '2.4', '2.7', '1.1', '1.1', '2.0', '0.7', '0.3', '4.7', '1.7', '1.9', '0.7', '1.3', '3.5', '1.3', '2.2', '1.8', '2.7', '1.9', '1.0', '1.3', '0.6', '1.7', '2.1', '0.7', '4.1', '1.6', '0.5', '0.8', '1.0', '5.1', '1.6', '3.0', '1.6', '0.5', '1.2', '0.3', '0.9', '1.2', '1.5', '0.1', '2.1', '0.6', '1.0', '2.7', '2.1', '4.0', '2.3', '2.3', '7.5', '3.3', '0.9', '1.2', '2.4', '1.4', '3.0', '0.8', '0.5', '7.3', '0.6', '0.7', '2.4', '2.3', '0.9', '2.3', '0.7', '3.6', '2.2', '1.0', '1.4', '5.2', '3.6', '0.4', '4.0', '0.9', '0.9', '0.5', '1.2', '0.7', '2.5', '1.0', '1.3', '2.0', '0.8', '1.8', '1.3', '1.0', '3.0', '1.1', '0.2', '1.4', '1.3', '2.4', '1.4', '19.7', '0.5', '3.0', '3.5', '0.4', '1.5', '0.2', '1.8', '3.5', '1.7', '2.2', '1.2', '3.7', '1.8', '1.9', '3.2', '1.0', '1.2', '1.3', '1.3', '0.7', '1.6', '0.5', '0.6', '0.3', '0.1', '0.1', '1.1', '1.0', '1.8', '3.3', '0.1', '0.1', '0.3', '4.1', '1.6', '0.3', '1.2', '0.4', '-', '0.6', '-', '-', '-', '-', '-', '-', '-', '5', '-', '10', '22.2', '-', '25', '-', '-', '-']

221
['83.4', '96.4', '90.5', '96.5', '97.4', '91.5', '92.9', '91.1', '94.9', '93.0', '94.3', '96.6', '88.9', '92.1', '79.6', '96.5', 'N/A', '89.9', '90.4', 'N/A', '98.0', '95.3', '97.3', '94.2', '93.2', 'N/A', '96.8', '94.2', '94.1', '94.8', '91.7', '99.2', '91.1', '95.3', '97.8', '98.6', '96.4', '90.4', '98.0', '89.9', '96.6', '97.4', '97.5', '96.2', '93.1', '80.3', '93.3', '95.4', '98.3', '94.0', '84.7', '95.7', '96.6', '86.9', '97.6', '96.2', '91.2', '77.6', '94.4', '98.2', '81.5', '97.9', '97.6', '90.5', '95.4', '74.2', '92.6', '94.0', '96.6', '92.4', '97.7', '97.3', '36.1', '87.9', '84.0', '96.4', '84.0', '98.9', '87.8', '92.4', '68.5', '94.4', '97.8', '96.3', '94.6', '90.3', '97.0', '69.6', '98.1', '96.8', '84.6', '68.8', '91.2', '97.9', '96.0', '61.5', '98.1', '66.2', '97.9', '48.7', '94.4', '97.3', '92.5', '79.9', '97.8', '96.6', '92.3', '69.2', '98.3', '92.6', '99.4', '57.6', '98.8', '87.5', '96.4', '96.0', '89.0', '73.9', '84.1', '82.7', '94.3', '96.8', '86.7', '70.6', '98.6', '96.4', '92.6', '37.8', '86.5', '97.6', '94.9', '95.5', '76.5', '15.3', '89.4', '99.1', '95.8', '72.9', '96.4', '13.4', '48.1', '69.8', '88.5', '8.0', '98.6', '97.3', '40.4', '98.7', '99.3', '96.5', '98.7', '91.2', '91.3', '0.8', '97.7', '98.6', '98.8', '58.2', '97.6', '87.8', '97.6', '98.0', '54.9', '96.6', '57.4', '99.2', '96.7', '94.7', '89.9', '97.0', '15.1', '98.2', '96.4', '67.8', '97.5', '98.6', '95.8', '93.0', '97.7', '70.3', '98.2', '96.4', '97.1', '98.3', '98.6', '98.0', '88.2', '65.6', '25.5', '94.8', '87.1', '74.4', '98.0', '97.9', '96.7', '46.0', '98.6', '96.5', '36.0', '98.4', '22.0', '95.7', '84.3', '99.0', '99.4', '45.0', '100', '100', '96.2', '81.6', '100', '96.2', '95', '100', '80', '77.8', '100', '75', '100', '100', '100']

221
['103,987', '21,723', '84,540', '88,210', '63,738', '36,667', '68,357', '94,641', '70,350', '77,991', '80,519', '44,526', '37,114', '76,071', '19,224', '50,994', '61,586', '7,378', '30,897', '98,019', '155,588', '79,630', '37,348', '12,483', '32,139', '107,732', '56,157', '93,156', '4,300', '84,910', '5,229', '97,051', '83,608', '6,214', '73,213', '81,929', '81,127', '21,806', '72,141', '21,497', '62,080', '79,636', '14,271', '13,656', '25,315', '36,221', '60,611', '40,156', '43,553', '21,863', '57,164', '91,370', '71,687', '32,612', '87,512', '90,258', '102,593', '69,511', '79,841', '33,092', '29,282', '61,318', '50,405', '15,677', '102,291', '2,715', '2,395', '54,543', '154,736', '9,215', '123,653', '63,508', '25,664', '49,467', '11,293', '75,704', '3,229', '76,749', '62,442', '27,834', '3,334', '14,953', '812', '74,700', '2,963', '2,731', '72,620', '3,108', '46,039', '98,644', '7,270', '23,896', '17,864', '59,237', '3,192', '2,773', '159,365', '29,909', '3,059', '17,054', '64', '3,026', '11,946', '29,819', '61,051', '2,322', '133,475', '1,589', '112,680', '27,984', '10,674', '16,788', '1,821', '2,639', '2,537', '1,522', '2,839', '423', '1,149', '829', '1,825', '57,625', '2,427', '21,984', '69,291', '1,191', '31,767', '89,215', '1,438', '11,171', '1,792', '4,380', '34,333', '71,070', '24,339', '67,538', '16,231', '1,523', '1,902', '41,867', '935', '710', '148,657', '594', '179,434', '1,659', '140', '644', '1,395', '32,792', '75,073', '2,229', '31,441', '32,452', '1,587', '11,732', '104,078', '5,185', '964', '6,660', '6,207', '671', '1,162', '1,476', '231', '19,429', '2,501', '226', '1,529', '28,416', '441', '150,010', '301', '612', '128,313', '14,076', '4,499', '1,944', '79,417', '615', '564', '60,057', '64,956', '40,207', '62,608', '10,778', '19,794', '55,165', '2,532', '284', '2,513', '1,338', '62,274', '18,804', '12,897', '101,752', '15,717', '9,266', '9', '-', '6,579', '585', '8,203', '2,653', '1,431', '452', '7,265', '18,103', '82', '881', '33,708', '4,487', '4,006', '29', '17', '-', '68', '13', '15', '329', '9']

221
['331,002,651', '1,380,004,385', '212,559,417', '65,273,511', '84,339,067', '145,934,462', '67,886,011', '45,195,774', '60,461,826', '50,882,891', '46,754,778', '83,783,942', '83,992,949', '37,846,611', '128,932,753', '43,733,762', '32,971,854', '273,523,615', '59,308,690', '17,134,872', '10,708,981', '19,116,201', '37,742,154', '109,581,078', '40,222,493', '10,099,265', '19,237,691', '11,589,623', '220,892,340', '10,196,709', '164,689,383', '8,655,535', '9,660,351', '126,476,461', '10,203,134', '8,737,371', '8,654,622', '32,365,999', '9,006,398', '29,136,808', '9,890,402', '6,825,445', '36,910,560', '34,813,871', '17,643,054', '11,673,021', '6,948,445', '10,423,054', '9,449,323', '18,776,707', '7,132,538', '4,314,767', '5,459,642', '11,818,619', '4,105,267', '3,989,167', '3,473,730', '5,094,118', '4,270,571', '10,139,177', '10,847,910', '5,101,414', '5,792,202', '17,915,568', '2,722,289', '102,334,404', '114,963,588', '4,937,786', '1,701,575', '28,435,940', '2,078,938', '4,033,963', '9,904,607', '5,106,626', '21,413,249', '2,963,243', '69,799,978', '2,881,053', '3,280,819', '6,871,292', '53,771,296', '11,326,616', '206,139,589', '2,083,374', '51,269,185', '54,409,800', '1,886,198', '43,851,044', '2,877,797', '1,326,535', '18,383,955', '5,421,241', '6,524,195', '1,810,463', '33,469,203', '38,928,346', '628,066', '3,278,290', '31,072,940', '5,540,720', '1,439,323,776', '26,545,863', '6,486,205', '2,540,905', '1,207,359', '31,255,435', '540,544', '45,741,007', '625,978', '2,351,627', '5,850,342', '2,961,167', '26,378,274', '16,718,965', '16,743,927', '27,691,018', '14,862,924', '89,561,403', '32,866,272', '43,849,260', '19,129,952', '555,987', '12,952,218', '1,399,488', '441,543', '25,499,884', '895,312', '298,682', '17,500,658', '2,225,734', '13,132,795', '4,649,658', '586,632', '272,815', '786,552', '280,908', '1,160,164', '11,402,528', '8,947,024', '400,124', '15,893,222', '20,250,833', '98,347', '23,816,775', '77,265', '8,278,724', '97,338,579', '20,903,273', '9,537,645', '397,628', '164,093', '5,518,087', '393,244', '375,265', '7,496,981', '988,000', '106,766', '2,142,249', '11,193,725', '1,318,445', '1,402,985', '12,123,200', '6,624,554', '4,829,767', '29,825,964', '341,243', '2,416,668', '24,206,644', '3,546,421', '183,627', '11,890,784', '33,931', '16,425,864', '7,976,983', '33,691', '287,375', '869,601', '1,968,001', '38,128', '5,057,681', '4,822,233', '42,876', '39,242', '62,278', '38,717', '219,159', '110,940', '38,666', '896,445', '7,275,560', '771,608', '1,271,768', '26,223', '85,033', '97,929', '9,877', '48,863', '65,722', '59,734,218', '-', '53,199', '437,479', '30,231', '71,986', '112,523', '285,498', '15,003', '3,480', '649,335', '56,770', '801', '5,794', '4,992', '686,884', '597,339', '-', '59,190', '307,145', '198,414', '6,077', '115,023']

,국가,확진자,치료중,위중증,사망자,완치,치명(%),완치(%),발생률,인구수
0,미국🇺🇸,"34,406,059\n(+4,219)","5,077,577\n(-12,311)","3,957\n(-38)","617,166\n(+75)","28,711,316\n(+16,455)",1.8,83.4,"103,987","331,002,651"
1,인도🇮🇳,"29,965,292\n(+54,052)","681,288\n(-44,081)","8,944","388,828\n(+1,667)","28,895,176\n(+96,466)",1.3,96.4,"21,723","1,380,004,385"
2,브라질🇧🇷,"17,927,928\n(+44,178)","1,205,772\n(+6,739)","8,318","501,918\n(+1,050)","16,220,238\n(+36,389)",2.8,90.5,"84,540","212,559,417"
3,프랑스🇫🇷,"5,757,311\n(+1,815)","89,987\n(+604)","1,703","110,738\n(+14)","5,556,586\n(+1,197)",1.9,96.5,"88,210","65,273,511"
4,터키🇹🇷,"5,370,299\n(+5,091)","88,476\n(+809)",813\n(-16),"49,185\n(+63)","5,232,638\n(+4,219)",0.9,97.4,"63,738","84,339,067"
...,...,...,...,...,...,...,...,...,...,...
216,마셜 제도🇲🇭,4,0,N/A,0,4,-,100,68,"59,190"
217,바누아투🇻🇺,4,0,N/A,1,3,25,75,13,"307,145"
218,사모아🇼🇸,3,0,N/A,0,3,-,100,15,"198,414"
219,세인트헬레나🇸🇭,2,0,N/A,0,2,-,100,329,"6,077"
220,미크로네시아🇫🇲,1,0,N/A,0,1,-,100,9,"115,023"

In [4]:
##확인
for i in range(10):
    print(len(all_data[i]))

221
221
221
221
221
221
221
221
221
221

In [5]:
#합계값과 1일값 나누기

dat['확진자_합계'] = dat['확진자'].str.split('\n').str[0]
dat['확진자1일'] = dat['확진자'].str.split('\n').str[1]

dat['치료중_합계'] = dat['치료중'].str.split('\n').str[0]
dat['치료중1일'] = dat['치료중'].str.split('\n').str[1]

dat['위중증_합계'] = dat['위중증'].str.split('\n').str[0]
dat['위중증1일'] = dat['위중증'].str.split('\n').str[1]

dat['사망자합계'] = dat['사망자'].str.split('\n').str[0]
dat['사망자1일'] = dat['사망자'].str.split('\n').str[1]

dat['완치합계'] = dat['완치'].str.split('\n').str[0]
dat['완치1일'] = dat['완치'].str.split('\n').str[1]

dat = dat.drop( [ '확진자', '치료중','위중증','사망자', '완치'], axis=1)
dat.head()

,국가,치명(%),완치(%),발생률,인구수,확진자_합계,확진자1일,치료중_합계,치료중1일,위중증_합계,위중증1일,사망자합계,사망자1일,완치합계,완치1일
0,미국🇺🇸,1.8,83.4,"103,987","331,002,651","34,406,059","(+4,219)","5,077,577","(-12,311)","3,957",(-38),"617,166",(+75),"28,711,316","(+16,455)"
1,인도🇮🇳,1.3,96.4,"21,723","1,380,004,385","29,965,292","(+54,052)","681,288","(-44,081)","8,944",NaN,"388,828","(+1,667)","28,895,176","(+96,466)"
2,브라질🇧🇷,2.8,90.5,"84,540","212,559,417","17,927,928","(+44,178)","1,205,772","(+6,739)","8,318",NaN,"501,918","(+1,050)","16,220,238","(+36,389)"
3,프랑스🇫🇷,1.9,96.5,"88,210","65,273,511","5,757,311","(+1,815)","89,987",(+604),"1,703",NaN,"110,738",(+14),"5,556,586","(+1,197)"
4,터키🇹🇷,0.9,97.4,"63,738","84,339,067","5,370,299","(+5,091)","88,476",(+809),813,(-16),"49,185",(+63),"5,232,638","(+4,219)"

In [6]:
#특수문자 제거

dat['확진자_합계'] = dat['확진자_합계'].str.replace(pat=r'[,]', repl=r'', regex=True)
dat['확진자1일'] = dat['확진자1일'].str.replace(pat=r'[,()]', repl=r'', regex=True)

dat['치료중_합계'] = dat['치료중_합계'].str.replace(pat=r'[,]', repl=r'', regex=True)
dat['치료중1일'] = dat['치료중1일'].str.replace(pat=r'[,()]', repl=r'', regex=True)

dat['위중증_합계'] = dat['위중증_합계'].str.replace(pat=r'[,]', repl=r'', regex=True)
dat['위중증1일'] = dat['위중증1일'].str.replace(pat=r'[,()]', repl=r'', regex=True)

dat['사망자합계'] = dat['사망자합계'].str.replace(pat=r'[,]', repl=r'', regex=True)
dat['사망자1일'] = dat['사망자1일'].str.replace(pat=r'[,()]', repl=r'', regex=True)

dat['완치합계'] = dat['완치합계'].str.replace(pat=r'[,]', repl=r'', regex=True)
dat['완치1일'] = dat['완치1일'].str.replace(pat=r'[,()]', repl=r'', regex=True)

dat['발생률'] = dat['발생률'].str.replace(pat=r'[,]', repl=r'', regex=True)
dat['인구수'] = dat['인구수'].str.replace(pat=r'[,]', repl=r'', regex=True)
dat.head()

,국가,치명(%),완치(%),발생률,인구수,확진자_합계,확진자1일,치료중_합계,치료중1일,위중증_합계,위중증1일,사망자합계,사망자1일,완치합계,완치1일
0,미국🇺🇸,1.8,83.4,103987,331002651,34406059,+4219,5077577,-12311,3957,-38,617166,+75,28711316,+16455
1,인도🇮🇳,1.3,96.4,21723,1380004385,29965292,+54052,681288,-44081,8944,NaN,388828,+1667,28895176,+96466
2,브라질🇧🇷,2.8,90.5,84540,212559417,17927928,+44178,1205772,+6739,8318,NaN,501918,+1050,16220238,+36389
3,프랑스🇫🇷,1.9,96.5,88210,65273511,5757311,+1815,89987,+604,1703,NaN,110738,+14,5556586,+1197
4,터키🇹🇷,0.9,97.4,63738,84339067,5370299,+5091,88476,+809,813,-16,49185,+63,5232638,+4219

In [7]:
#일 확진자 많은 순서대로 내림차순 정렬

import pandas as pd
data_ = dat
data_['확진자1일'] = data_['확진자1일'].str.replace(pat=r'[,()+]', repl=r'', regex=True)
data_ = data_.astype({'확진자1일': 'float32'})
data_ = data_.sort_values("확진자1일",axis=0, ascending=False)
data_

,국가,치명(%),완치(%),발생률,인구수,확진자_합계,확진자1일,치료중_합계,치료중1일,위중증_합계,위중증1일,사망자합계,사망자1일,완치합계,완치1일
1,인도🇮🇳,1.3,96.4,21723,1380004385,29965292,54052.0,681288,-44081,8944,NaN,388828,+1667,28895176,+96466
2,브라질🇧🇷,2.8,90.5,84540,212559417,17927928,44178.0,1205772,+6739,8318,NaN,501918,+1050,16220238,+36389
9,콜롬비아🇨🇴,2.5,93.0,77991,50882891,3945166,27818.0,178071,+4345,8155,NaN,99934,+599,3667161,+22874
5,러시아🇷🇺,2.4,91.5,36667,145934462,5334204,17378.0,326070,+8577,2300,NaN,129801,+440,4878333,+8361
17,인도네시아🇮🇩,2.7,89.9,7378,273523615,2004445,14536.0,147728,+5009,N/A,NaN,54956,+294,1801761,+9233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,마셜 제도🇲🇭,-,100,68,59190,4,NaN,0,NaN,N/A,NaN,0,NaN,4,NaN
217,바누아투🇻🇺,25,75,13,307145,4,NaN,0,NaN,N/A,NaN,1,NaN,3,NaN
218,사모아🇼🇸,-,100,15,198414,3,NaN,0,NaN,N/A,NaN,0,NaN,3,NaN
219,세인트헬레나🇸🇭,-,100,329,6077,2,NaN,0,NaN,N/A,NaN,0,NaN,2,NaN
220,미크로네시아🇫🇲,-,100,9,115023,1,NaN,0,NaN,N/A,NaN,0,NaN,1,NaN

In [9]:
#저장
dat.to_excel("coronaboard_0622_yesterday.xlsx",index=False)
dat.to_csv("coronaboard_0622_yesterday.csv",index=False)
data_.to_excel("coronaboard_0622_yesterday_top10.xlsx", index=False)
data_.to_csv("coronaboard_0622_yesterday_top10.csv", index=False)
os.listdir( os.getcwd() )

['.ipynb_checkpoints',
 'coronaboard_0622_today.csv',
 'coronaboard_0622_today.xlsx',
 'coronaboard_0622_today_top10.csv',
 'coronaboard_0622_today_top10.xlsx',
 'coronaboard_0622_yesterday.csv',
 'coronaboard_0622_yesterday.xlsx',
 'coronaboard_0622_yesterday_top10.csv',
 'coronaboard_0622_yesterday_top10.xlsx',
 'corona_board_crawling-Copy1.ipynb',
 'corona_board_crawling.ipynb',
 '[Group]corona_board_crawling_0622.ipynb',
 '[Group]corona_board_crawling_chelsea.ipynb']